inherit_gem:
  aaf-gumboot: aaf-rubocop.yml

Rails:
  Enabled: false

Style/RescueStandardError:
  Exclude:
    - lib/discovery_service/event_consignment.rb

Style/MixinUsage:
  Exclude:
    - bin/setup
