require: rubocop-rails

AllCops:
  NewCops: enable

inherit_from:
  - https://raw.githubusercontent.com/ausaccessfed/aaf-gumboot/develop/aaf-rubocop.yml

Rails:
  Enabled: false

Style/RescueStandardError:
  Exclude:
    - lib/discovery_service/event_consignment.rb

Style/MixinUsage:
  Exclude:
    - bin/setup
