---
:saml_service:
  :url: http://localhost:8080/entities

:groups:
  :aaf:
    - [discovery, aaf]
  :taukiri:
    - [discovery, taukiri]
  :edugain:
    - [discovery, aaf]
    - [discovery, taukiri]
    - [discovery, edugain]

:environment:
  :name: 'test'
  :status_url: 'http://status.test.aaf.edu.au'

:tag_groups:
  - :name: 'Australia'
    :tag: 'au'
  - :name: 'New Zealand'
    :tag: 'nz'
  - :name: 'International'
    :tag: '*'
