---
:saml_service:
  :url: http://localhost:8080/entities

:groups:
  :taukiri:
    :filters:
      - [tuakiri, other]
    :tag_groups:
      false
  :aaf:
    :filters:
      - [discovery, aaf]
      - [sp, aaf]
      - [idp, aaf]
      - [tuakiri]
    :tag_groups:
      - :name: 'Australia'
        :tag: 'aaf'
      - :name: 'New Zealand'
        :tag: 'tuakiri'
  :edugain:
    :filters:
      - [discovery, aaf]
      - [discovery, tuakiri]
      - [discovery, edugain]
    :tag_groups:
      - :name: 'Australia'
        :tag: 'aaf'
      - :name: 'New Zealand'
        :tag: 'tuakiri'
      - :name: 'International'
        :tag: '*'

:environment:
  :name: 'Test Environment'
  :status_url: 'http://status.test.aaf.edu.au'
